version: '3.1'

services:
        mongodb:
                image: mongo:latest
                container_name: mongodb
                environment:
                        - MONGO_DATA_DIR=/data/db
                        - MONGO_LOG_DIR=/dev/null
                volumes:
                        - ./data/db:/data/db
                ports:
                        - 27017:27017
                hostname: localhost
                command: mongod --smallfiles

        redis:
                container_name: redis
                image: redis
                ports:
                        - "6379:6379"
                volumes:
                        - ../data/redis:/data
                restart: always

        app:
                container_name: backend
                build: ./backend
                working_dir: /backend
                volumes:
                        - ./backend:/backend
                        - ~/.m2:/root/.m2
                command: mvn clean spring-boot:run
                depends_on:
                        - mongodb
                        - redis
                links:
                        - mongodb:mongo
                        - redis:redis

        tomcatserver:
                image: tomcat:latest
                container_name: tomcat
                volumes:
                        - ./target/DPP.war:/backend/target/DPP-0.0.1.war
                ports:
                        - "8080:8080"
                hostname: localhost
                depends_on:
                        - app
                links:
                        - mongodb:mongo
                        - redis:redis
                        - app:backend

