package com.anirbandc.ws.web.message;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * This class acts as the template for all types of responses generated by the
 * server.<br/>
 * 
 * <b>status</b>: custom status message<br/>
 * <b>status_message</b>: small explanation regarding response status
 * 
 * @author Anirban DC
 */
public abstract class AbstractResponse {
	@JsonProperty("status")
	private String status;

	@JsonProperty("status_message")
	private String statusMessage;

	/**
	 * @return status
	 */
	public final String getStatus() {
		return status;
	}

	/**
	 * @return statusMessage
	 */
	public final String getStatusMessage() {
		return statusMessage;
	}

	/**
	 * @param status
	 */
	public final void setStatus(String status) {
		this.status = status;
	}

	/**
	 * @param statusMessage
	 */
	public final void setStatusMessage(String statusMessage) {
		this.statusMessage = statusMessage;
	}
}
